steps:
- name:'gcr.io/cloud-builders/gcloud'
  args:['cp','gs://buk-temp/*','bigquery://My First Project/karthikdata.karthik']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_gcs
  - --source=.
  - --trigger-bucket=buk-temp
  - --runtime=python37
  - --allow-unauthenticated
